### ISSUE TITLE
INTERFACE - Remove or hide admit button

### ISSUE THREAD

**Issue by jburnsthomas** [openmrs-indianaems/openmrs-indianaems-config#26]
INTERFACE - Admit to inpatient button can be removed or hidden

**Comment by bmamlin** [comment]
We might be able to remove the "Admit to inpatient" action through...

1. Removing the `Task: referenceapplication.simpleAdmission` privilege from the `Application: Enters ADT Events` role should theoretically not show the "Admit to inpatient" option for Standard Users; however, this didn't work for me in testing.

2. We could try to find a way to add this CSS to the clinician-facing patient dashboard:
```css
#referenceapplication\.realTime\.simpleAdmission {
    display: none;
}
```
